import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const categories = ["Logiciels", "Marketing", "Transport", "Fournitures", "Salaires", "Services", "Loyer", "Taxes", "Autres"] as const;
const expenseInput = z.object({ date: z.string().nullable().optional(), description: z.string().trim().min(1).max(200), category: z.enum(categories), amount: z.number().nonnegative(), currency: z.string().length(3).default("EUR") });

async function context() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { supabase, user: null, companyId: null }; const { data: member } = await supabase.from("company_members").select("company_id").eq("user_id", user.id).limit(1).maybeSingle(); return { supabase, user, companyId: member?.company_id || null }; }

export async function GET() { const { supabase, user, companyId } = await context(); if (!user) return NextResponse.json({ error: "not_authenticated" }, { status: 401 }); if (!companyId) return NextResponse.json({ expenses: [] }); const { data, error } = await supabase.from("expenses").select("id, description, category, amount, currency, expense_date, created_at, updated_at").eq("company_id", companyId).order("expense_date", { ascending: false, nullsFirst: false }); if (error) return NextResponse.json({ error: "expenses_unavailable" }, { status: 502 }); return NextResponse.json({ expenses: data }); }
export async function POST(request: Request) { const { supabase, user, companyId } = await context(); if (!user) return NextResponse.json({ error: "not_authenticated" }, { status: 401 }); if (!companyId) return NextResponse.json({ error: "company_required" }, { status: 409 }); const parsed = expenseInput.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "invalid_expense" }, { status: 400 }); const value = parsed.data; const { data, error } = await supabase.from("expenses").insert({ company_id: companyId, expense_date: value.date || null, description: value.description, category: value.category, amount: value.amount, currency: value.currency, supplier_id: null, document_id: null }).select().single(); if (error) return NextResponse.json({ error: "expense_create_failed" }, { status: 502 }); return NextResponse.json({ expense: data }, { status: 201 }); }