"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, CalendarClock } from "lucide-react";

type Deadline = { id: string; title: string; due_date: string; amount: number | null; status: string; deadline_type: string; source: string | null };
function statusLabel(status: string) { return ({ upcoming: "À venir", today: "Aujourd’hui", overdue: "En retard", completed: "Terminé" } as Record<string, string>)[status] || status; }
export default function DeadlinesPage() { const [deadlines, setDeadlines] = useState<Deadline[]>([]); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState(false); useEffect(() => { fetch("/api/deadlines").then((response) => response.json()).then((result) => { if (result.error) setError(true); else setDeadlines(result.deadlines || []); }).catch(() => setError(true)).finally(() => setIsLoading(false)); }, []); return <main className="deadlines-page"><div className="deadlines-inner"><div className="deadlines-top"><Link className="brand" href="/dashboard"><span className="brand-mark">A</span><span>AI Finance <em>OS</em></span></Link><Link className="text-link" href="/dashboard"><ArrowLeft size={14} /> Retour au dashboard</Link></div><div className="deadlines-heading"><p className="eyebrow">FINANCE</p><h1>Échéances</h1><p>Les dates issues de vos factures et de vos données enregistrées.</p></div>{error && <p className="invoice-message error">Impossible de charger les échéances.</p>}{isLoading ? <p className="deadline-empty">Chargement...</p> : deadlines.length === 0 ? <section className="deadline-empty"><CalendarClock size={25} /><p>Aucune échéance réelle pour le moment.</p></section> : <div>{deadlines.map((deadline) => <article className="deadline-row" key={`${deadline.deadline_type}-${deadline.id}`}><span><strong>{deadline.title}</strong><small>{deadline.source || deadline.deadline_type}</small></span><span>{new Date(`${deadline.due_date}T00:00:00`).toLocaleDateString("fr-FR")}</span><strong>{deadline.amount === null ? "" : Number(deadline.amount).toLocaleString("fr-FR", { style: "currency", currency: "EUR" })}</strong><span className={`deadline-status ${deadline.status}`}>{statusLabel(deadline.status)}</span></article>)}</div>}</div></main>; }
