"use client";

import { FormEvent, useEffect, useState } from "react";
import { Building2, Check, CircleUserRound, ImagePlus, LockKeyhole, LogOut, Palette, Save, ShieldAlert, Sparkles, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { defaultAppPreferences, type AppPreferences, type Language } from "@/lib/app/types";

type Section = "profile" | "company" | "appearance" | "language" | "notifications" | "security" | "subscription";
type Notice = { type: "success" | "error"; message: string } | null;
type CompanyForm = { name: string; trade_name: string; legal_form: string; logo_url: string; country: string; currency: string; address: string; address_complement: string; city: string; postal_code: string; siret: string; siren: string; vat_number: string; industry: string };
type ProfileForm = { first_name: string; last_name: string; avatar_url: string | null };

const sections: { id: Section; label: string; icon: typeof CircleUserRound }[] = [
  { id: "profile", label: "Mon profil", icon: CircleUserRound }, { id: "company", label: "Entreprise", icon: Building2 }, { id: "appearance", label: "Apparence", icon: Palette }, { id: "language", label: "Langue", icon: Sparkles }, { id: "notifications", label: "Notifications", icon: Check }, { id: "security", label: "Sécurité", icon: LockKeyhole }, { id: "subscription", label: "Abonnement", icon: ShieldAlert },
];
const languages: { value: Language; label: string }[] = [{ value: "fr", label: "Français" }, { value: "en", label: "English" }, { value: "es", label: "Español" }, { value: "pt", label: "Português" }, { value: "it", label: "Italiano" }, { value: "de", label: "Deutsch" }, { value: "zh", label: "中文" }, { value: "ja", label: "日本語" }, { value: "ar", label: "العربية" }];
const emptyCompany: CompanyForm = { name: "", trade_name: "", legal_form: "", logo_url: "", country: "", currency: "EUR", address: "", address_complement: "", city: "", postal_code: "", siret: "", siren: "", vat_number: "", industry: "" };

function readSection(value: string | null): Section { return sections.some((section) => section.id === value) ? value as Section : "profile"; }

export default function SettingsPage() {
  const [supabase] = useState(createClient);
  const [section, setSection] = useState<Section>("profile");
  const [userId, setUserId] = useState(""); const [email, setEmail] = useState("");
  const [profile, setProfile] = useState<ProfileForm>({ first_name: "", last_name: "", avatar_url: null });
  const [company, setCompany] = useState<CompanyForm>(emptyCompany); const [companyId, setCompanyId] = useState("");
  const [preferences, setPreferences] = useState<AppPreferences>(defaultAppPreferences);
  const [password, setPassword] = useState(""); const [passwordConfirmation, setPasswordConfirmation] = useState("");
  const [notice, setNotice] = useState<Notice>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);

  useEffect(() => {
    setSection(readSection(new URLSearchParams(window.location.search).get("section")));
    async function load() {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) { setLoading(false); return; }
      setUserId(user.id); setEmail(user.email || "");
      const [{ data: profileData, error: profileError }, { data: preferenceData, error: preferenceError }, { data: membership, error: membershipError }] = await Promise.all([
        supabase.from("profiles").select("first_name, last_name, avatar_url").eq("id", user.id).maybeSingle(),
        supabase.from("user_preferences").select("language, theme, density, sidebar_compact, reduce_motion, animation_mode, dashboard_preferences, notifications").eq("user_id", user.id).maybeSingle(),
        supabase.from("company_members").select("company_id").eq("user_id", user.id).limit(1).maybeSingle(),
      ]);
      if (profileError) console.error("Profile settings lookup failed", profileError.message);
      if (preferenceError) console.error("Preference settings lookup failed", preferenceError.message);
      if (membershipError) console.error("Company membership lookup failed", membershipError.message);
      if (profileData) setProfile(profileData);
      if (preferenceData) setPreferences((current) => ({ ...current, ...preferenceData, notifications: { ...current.notifications, ...(preferenceData.notifications as Record<string, boolean>) }, dashboard_preferences: { ...current.dashboard_preferences, ...(preferenceData.dashboard_preferences as Partial<AppPreferences["dashboard_preferences"]>) } }));
      if (membership?.company_id) { setCompanyId(membership.company_id); const { data: companyData, error: companyError } = await supabase.from("companies").select("name, trade_name, legal_form, logo_url, country, currency, address, address_complement, city, postal_code, siret, siren, vat_number, industry").eq("id", membership.company_id).maybeSingle(); if (companyError) { console.error("Company settings lookup failed", companyError.message); showNotice("error", "Impossible de charger les informations de l’entreprise."); } else if (companyData) setCompany({ name: companyData.name, trade_name: companyData.trade_name || "", legal_form: companyData.legal_form || "", logo_url: companyData.logo_url || "", country: companyData.country || "", currency: companyData.currency, address: companyData.address || "", address_complement: companyData.address_complement || "", city: companyData.city || "", postal_code: companyData.postal_code || "", siret: companyData.siret || "", siren: companyData.siren || "", vat_number: companyData.vat_number || "", industry: companyData.industry || "" }); }
      setLoading(false);
    }
    void load();
  }, [supabase]);

  function showNotice(type: "success" | "error", message: string) { setNotice({ type, message }); window.setTimeout(() => setNotice(null), 4000); }
  function selectSection(next: Section) { setSection(next); window.history.replaceState(null, "", `/settings?section=${next}`); }
  function applyPreferences(next: AppPreferences) { setPreferences(next); const theme = next.theme === "system" ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light") : next.theme; document.documentElement.dataset.theme = theme; document.documentElement.dataset.density = next.density; document.documentElement.dataset.animation = next.animation_mode; document.documentElement.dir = next.language === "ar" ? "rtl" : "ltr"; document.documentElement.lang = next.language; window.localStorage.setItem("ai-finance-preferences", JSON.stringify(next)); }
  async function savePreferences(next: AppPreferences) { applyPreferences(next); if (!userId) return; setSaving(true); const { error } = await supabase.from("user_preferences").upsert({ user_id: userId, language: next.language, theme: next.theme, density: next.density, sidebar_compact: next.sidebar_compact, reduce_motion: next.animation_mode !== "enabled", animation_mode: next.animation_mode, dashboard_preferences: next.dashboard_preferences, notifications: next.notifications }); setSaving(false); showNotice(error ? "error" : "success", error ? "Impossible d’enregistrer ces préférences." : "Modifications enregistrées."); }
  async function saveProfile(event: FormEvent) { event.preventDefault(); if (!profile.first_name.trim() || !profile.last_name.trim()) return showNotice("error", "Le prénom et le nom sont obligatoires."); setSaving(true); const { error: profileError } = await supabase.from("profiles").update({ first_name: profile.first_name.trim(), last_name: profile.last_name.trim(), avatar_url: profile.avatar_url }).eq("id", userId); const { error: emailError } = email ? await supabase.auth.updateUser({ email }) : { error: null }; setSaving(false); showNotice(profileError || emailError ? "error" : "success", profileError || emailError ? "Impossible d’enregistrer le profil." : "Modifications enregistrées."); }
  async function uploadAvatar(file: File) { if (!userId) return; setSaving(true); const path = `${userId}/avatar-${Date.now()}.${file.name.split(".").pop() || "jpg"}`; const { error: uploadError } = await supabase.storage.from("avatars").upload(path, file, { upsert: true, contentType: file.type }); if (uploadError) { setSaving(false); return showNotice("error", "Impossible d’ajouter cette photo."); } const { data } = supabase.storage.from("avatars").getPublicUrl(path); setProfile((current) => ({ ...current, avatar_url: data.publicUrl })); setSaving(false); showNotice("success", "Photo ajoutée."); }
  async function saveCompany(event: FormEvent) { event.preventDefault(); const siret = company.siret.replace(/\s/g, ""); const siren = company.siren.replace(/\s/g, ""); if (!company.name.trim()) return showNotice("error", "Le nom de l’entreprise est obligatoire."); if (siret && !/^\d{14}$/.test(siret)) return showNotice("error", "Le SIRET doit contenir 14 chiffres."); if (siren && !/^\d{9}$/.test(siren)) return showNotice("error", "Le SIREN doit contenir 9 chiffres."); if (company.vat_number && !/^FR[A-Z0-9]{2}\d{9}$/.test(company.vat_number.replace(/\s/g, "").toUpperCase())) return showNotice("error", "Le numéro de TVA doit commencer par FR et contenir 11 caractères après le préfixe."); setSaving(true); const values = { ...company, name: company.name.trim(), trade_name: company.trade_name.trim() || null, legal_form: company.legal_form.trim() || null, logo_url: company.logo_url || null, address_complement: company.address_complement.trim() || null, siret: siret || null, siren: siren || null, vat_number: company.vat_number.replace(/\s/g, "").toUpperCase() || null }; let result = companyId ? await supabase.from("companies").update(values).eq("id", companyId) : await supabase.rpc("create_company", { company_name: values.name }); if (!result.error && !companyId && result.data) { setCompanyId(result.data); result = await supabase.from("companies").update(values).eq("id", result.data); } if (result.error) console.error("Company settings save failed", result.error.message); setSaving(false); showNotice(result.error ? "error" : "success", result.error ? "Impossible d’enregistrer les modifications de l’entreprise." : "Modifications enregistrées."); }
  async function changePassword(event: FormEvent) { event.preventDefault(); if (password.length < 10 || password !== passwordConfirmation) return showNotice("error", "Le mot de passe doit contenir 10 caractères et les deux champs doivent correspondre."); setSaving(true); const { error } = await supabase.auth.updateUser({ password }); setSaving(false); if (!error) { setPassword(""); setPasswordConfirmation(""); } showNotice(error ? "error" : "success", error ? "Impossible de modifier le mot de passe." : "Modifications enregistrées."); }
  async function logout() { await supabase.auth.signOut(); window.location.href = "/login"; }
  async function deleteAccount() { if (!window.confirm("Cette action supprimera définitivement votre compte et ses données. Confirmer ?")) return; setSaving(true); const { error } = await supabase.rpc("delete_my_account"); if (error) { setSaving(false); return showNotice("error", "Impossible de supprimer le compte."); } await supabase.auth.signOut(); window.location.href = "/"; }

  if (loading) return <main className="settings-page"><div className="settings-loading">Chargement des paramètres...</div></main>;
  return <main className="settings-page"><div className="settings-heading"><p className="eyebrow">CONFIGURATION</p><h1>Paramètres</h1><p>Votre espace, selon vos besoins.</p></div><div className="settings-layout"><nav className="settings-nav" aria-label="Navigation des paramètres"><div>{sections.map(({ id, label, icon: Icon }) => <button className={section === id ? "active" : ""} key={id} onClick={() => selectSection(id)}><Icon size={16} />{label}</button>)}</div><button onClick={() => void logout}><LogOut size={16} />Se déconnecter</button></nav><section className="settings-panel">{notice && <p className={`settings-status ${notice.type}`} role="status">{notice.message}</p>}{section === "profile" && <ProfilePanel profile={profile} email={email} saving={saving} onChange={setProfile} onEmailChange={setEmail} onSave={saveProfile} onUpload={uploadAvatar} />}{section === "company" && <CompanyPanel company={company} configured={Boolean(companyId)} saving={saving} onChange={setCompany} onSave={saveCompany} />}{section === "appearance" && <AppearancePanel preferences={preferences} saving={saving} onSave={savePreferences} />}{section === "language" && <LanguagePanel preferences={preferences} saving={saving} onSave={savePreferences} />}{section === "notifications" && <NotificationPanel preferences={preferences} saving={saving} onSave={savePreferences} />}{section === "security" && <SecurityPanel email={email} password={password} confirmation={passwordConfirmation} saving={saving} onPassword={setPassword} onConfirmation={setPasswordConfirmation} onChangePassword={changePassword} onLogoutOthers={() => void supabase.auth.signOut({ scope: "others" }).then(() => showNotice("success", "Les autres sessions ont été déconnectées."))} onDelete={deleteAccount} />}{section === "subscription" && <SubscriptionPanel />}</section></div></main>;
}

function PanelHeader({ title, description }: { title: string; description: string }) { return <div className="panel-title"><h2>{title}</h2><p>{description}</p></div>; }
function ProfilePanel({ profile, email, saving, onChange, onEmailChange, onSave, onUpload }: { profile: ProfileForm; email: string; saving: boolean; onChange: (profile: ProfileForm) => void; onEmailChange: (email: string) => void; onSave: (event: FormEvent) => void; onUpload: (file: File) => void }) { return <><PanelHeader title="Mon profil" description="Les informations de votre compte." /><form className="settings-form" onSubmit={onSave}><div className="profile-photo-row"><div className="profile-photo" role="img" aria-label="Photo de profil" style={profile.avatar_url ? { backgroundImage: `url(${profile.avatar_url})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}>{!profile.avatar_url && <CircleUserRound size={28} />}</div><label className="button button-light"><ImagePlus size={15} />Ajouter une photo<input className="visually-hidden" type="file" accept="image/*" onChange={(event) => { const file = event.target.files?.[0]; if (file) onUpload(file); }} /></label>{profile.avatar_url && <button type="button" className="text-link" onClick={() => onChange({ ...profile, avatar_url: null })}>Supprimer</button>}</div><div className="form-grid"><label>Prénom<input value={profile.first_name} onChange={(event) => onChange({ ...profile, first_name: event.target.value })} /></label><label>Nom<input value={profile.last_name} onChange={(event) => onChange({ ...profile, last_name: event.target.value })} /></label></div><label>Email<input type="email" value={email} onChange={(event) => onEmailChange(event.target.value)} /></label><button className="button button-dark" disabled={saving}><Save size={15} />{saving ? "Enregistrement..." : "Enregistrer"}</button></form></>; }
function CompanyPanel({ company, configured, saving, onChange, onSave }: { company: CompanyForm; configured: boolean; saving: boolean; onChange: (company: CompanyForm) => void; onSave: (event: FormEvent) => void }) { return <><PanelHeader title="Entreprise" description={configured ? "Les informations de votre entreprise." : "Aucune entreprise configurée. Vous pouvez continuer à utiliser l’application sans entreprise."} /><form className="settings-form" onSubmit={onSave}><div className="form-grid"><label>Nom de l’entreprise<input value={company.name} onChange={(event) => onChange({ ...company, name: event.target.value })} /></label><label>Nom commercial<input value={company.trade_name} onChange={(event) => onChange({ ...company, trade_name: event.target.value })} /></label><label>Forme juridique<input value={company.legal_form} onChange={(event) => onChange({ ...company, legal_form: event.target.value })} /></label><label>Secteur d’activité<input value={company.industry} onChange={(event) => onChange({ ...company, industry: event.target.value })} /></label><label>SIRET<input inputMode="numeric" value={company.siret} onChange={(event) => onChange({ ...company, siret: event.target.value })} /></label><label>SIREN<input inputMode="numeric" value={company.siren} onChange={(event) => onChange({ ...company, siren: event.target.value })} /></label><label>Numéro de TVA<input value={company.vat_number} onChange={(event) => onChange({ ...company, vat_number: event.target.value })} /></label><label>Devise<select value={company.currency} onChange={(event) => onChange({ ...company, currency: event.target.value })}><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option></select></label><label>Adresse<input value={company.address} onChange={(event) => onChange({ ...company, address: event.target.value })} /></label><label>Complément d’adresse<input value={company.address_complement} onChange={(event) => onChange({ ...company, address_complement: event.target.value })} /></label><label>Code postal<input value={company.postal_code} onChange={(event) => onChange({ ...company, postal_code: event.target.value })} /></label><label>Ville<input value={company.city} onChange={(event) => onChange({ ...company, city: event.target.value })} /></label><label>Pays<input value={company.country} onChange={(event) => onChange({ ...company, country: event.target.value })} /></label></div><button className="button button-dark" disabled={saving}><Save size={15} />{saving ? "Enregistrement..." : "Enregistrer"}</button></form></>; }
function AppearancePanel({ preferences, saving, onSave }: { preferences: AppPreferences; saving: boolean; onSave: (next: AppPreferences) => void }) { return <><PanelHeader title="Apparence" description="Adaptez l’interface à votre façon de travailler." /><Choice title="Thème" options={[["light", "Clair"], ["dark", "Sombre"], ["system", "Système"]]} value={preferences.theme} onChange={(value) => onSave({ ...preferences, theme: value as AppPreferences["theme"] })} /><Choice title="Densité de l’interface" options={[["compact", "Compacte"], ["standard", "Standard"], ["comfortable", "Confortable"]]} value={preferences.density} onChange={(value) => onSave({ ...preferences, density: value as AppPreferences["density"] })} /><Choice title="Animations" options={[["enabled", "Activées"], ["reduced", "Réduites"], ["disabled", "Désactivées"]]} value={preferences.animation_mode} onChange={(value) => onSave({ ...preferences, animation_mode: value as AppPreferences["animation_mode"] })} /><label className="toggle-row"><input type="checkbox" checked={preferences.sidebar_compact} onChange={(event) => onSave({ ...preferences, sidebar_compact: event.target.checked })} />Sidebar réduite</label>{saving && <p className="settings-saving">Enregistrement...</p>}</>; }
function Choice({ title, options, value, onChange }: { title: string; options: [string, string][]; value: string; onChange: (value: string) => void }) { return <fieldset><legend>{title}</legend><div className="choice-row">{options.map(([option, label]) => <button type="button" className={value === option ? "selected" : ""} key={option} onClick={() => onChange(option)}>{label}{value === option && <Check size={15} />}</button>)}</div></fieldset>; }
function LanguagePanel({ preferences, saving, onSave }: { preferences: AppPreferences; saving: boolean; onSave: (next: AppPreferences) => void }) { return <><PanelHeader title="Langue" description="Le français est la langue par défaut. Le changement s’applique à la navigation." /><div className="language-list">{languages.map((language) => <button type="button" className={preferences.language === language.value ? "selected" : ""} key={language.value} onClick={() => onSave({ ...preferences, language: language.value })}>{language.label}{preferences.language === language.value && <Check size={15} />}</button>)}</div>{preferences.language === "ar" && <p className="settings-hint">L’interface passe en direction droite à gauche pour l’arabe.</p>}{saving && <p className="settings-saving">Enregistrement...</p>}</>; }
function NotificationPanel({ preferences, saving, onSave }: { preferences: AppPreferences; saving: boolean; onSave: (next: AppPreferences) => void }) { const items: { key: keyof AppPreferences["notifications"]; label: string }[] = [{ key: "deadlines_new", label: "Nouvelles échéances" }, { key: "deadlines_soon", label: "Échéances proches" }, { key: "overdue_invoices", label: "Factures en retard" }, { key: "financial_analysis", label: "Analyses financières" }, { key: "ai_recommendations", label: "Recommandations IA" }, { key: "financial_alerts", label: "Alertes financières" }, { key: "email", label: "Notifications par email" }]; return <><PanelHeader title="Notifications" description="Préparez les préférences d’alerte. Aucun email n’est envoyé à ce stade." />{items.map((item) => <label className="toggle-row" key={item.key}><input type="checkbox" checked={preferences.notifications[item.key]} onChange={(event) => onSave({ ...preferences, notifications: { ...preferences.notifications, [item.key]: event.target.checked } })} />{item.label}</label>)}{saving && <p className="settings-saving">Enregistrement...</p>}</>; }
function SecurityPanel({ email, password, confirmation, saving, onPassword, onConfirmation, onChangePassword, onLogoutOthers, onDelete }: { email: string; password: string; confirmation: string; saving: boolean; onPassword: (value: string) => void; onConfirmation: (value: string) => void; onChangePassword: (event: FormEvent) => void; onLogoutOthers: () => void; onDelete: () => void }) { return <><PanelHeader title="Sécurité" description="Gérez l’accès à votre compte Supabase." /><form className="settings-form" onSubmit={onChangePassword}><h3>Modifier le mot de passe</h3><label>Nouveau mot de passe<input type="password" minLength={10} value={password} onChange={(event) => onPassword(event.target.value)} /></label><label>Confirmer le mot de passe<input type="password" minLength={10} value={confirmation} onChange={(event) => onConfirmation(event.target.value)} /></label><button className="button button-dark" disabled={saving}><LockKeyhole size={15} />Modifier le mot de passe</button></form><div className="settings-subform"><h3>Adresse email</h3><p>{email || "Aucune adresse email disponible"}</p><p>La modification d’adresse utilise la confirmation sécurisée Supabase.</p></div><div className="settings-subform"><h3>Sessions</h3><p>Session actuelle : {email || "compte connecté"}</p><button type="button" className="button button-light" onClick={onLogoutOthers}>Déconnecter les autres sessions</button></div><div className="danger-zone"><h3>Zone dangereuse</h3><p>La suppression du compte est définitive et demande une confirmation explicite.</p><button type="button" className="button button-danger" onClick={onDelete}><Trash2 size={15} />Supprimer mon compte</button></div></>; }
function SubscriptionPanel() { const plans = [{ name: "Free", description: "Pour découvrir l’espace financier.", features: ["Navigation complète", "Préférences utilisateur"] }, { name: "Pro", description: "Pour les équipes qui structurent leur activité.", features: ["Fonctionnalités avancées à venir", "Support prioritaire à venir"] }, { name: "Entreprise", description: "Pour les organisations multi-équipes.", features: ["Contrats personnalisés à venir", "Contrôle administrateur à venir"] }]; return <><PanelHeader title="Abonnement" description="Les plans sont préparés pour une future intégration Stripe. Aucun paiement n’est actif." /><div className="plans-grid">{plans.map((plan) => <article className="plan-card" key={plan.name}><h3>{plan.name}</h3><p>{plan.description}</p><ul>{plan.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><span className="plan-status">Préparation Stripe</span></article>)}</div></>; }