"use client";

import Link from "next/link";
import { type FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Plus, Search, Trash2 } from "lucide-react";

type Expense = { id: string; description: string; category: string; amount: number; currency: string; expense_date: string | null };
type Form = { date: string; description: string; category: string; amount: string };
const initialForm: Form = { date: "", description: "", category: "Autres", amount: "" };
const categories = ["Logiciels", "Marketing", "Transport", "Fournitures", "Salaires", "Services", "Loyer", "Taxes", "Autres"];

export default function ExpensesPage() {
  const [expenses, setExpenses] = useState<Expense[]>([]); const [form, setForm] = useState(initialForm); const [showForm, setShowForm] = useState(false); const [search, setSearch] = useState(""); const [isLoading, setIsLoading] = useState(true); const [isSaving, setIsSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function load() { setIsLoading(true); const response = await fetch("/api/expenses"); const result = await response.json().catch(() => null); if (response.ok) setExpenses(result.expenses || []); else setMessage("Impossible de charger les dépenses."); setIsLoading(false); }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setIsSaving(true); const response = await fetch("/api/expenses", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, amount: Number(form.amount), date: form.date || null }) }); setIsSaving(false); if (!response.ok) return setMessage("Impossible d’ajouter la dépense."); setForm(initialForm); setShowForm(false); setMessage("Dépense ajoutée."); await load(); }
  async function remove(id: string) { if (!window.confirm("Supprimer cette dépense ? Cette action est irréversible.")) return; const response = await fetch(`/api/expenses/${id}`, { method: "DELETE" }); if (!response.ok) return setMessage("Impossible de supprimer la dépense."); setExpenses((current) => current.filter((expense) => expense.id !== id)); setMessage("Dépense supprimée."); }
  const visible = useMemo(() => expenses.filter((expense) => `${expense.description} ${expense.category}`.toLowerCase().includes(search.toLowerCase())), [expenses, search]); const total = visible.reduce((sum, expense) => sum + Number(expense.amount), 0);
  return <main className="expenses-page"><div className="expenses-inner"><div className="expenses-top"><Link className="brand" href="/dashboard"><span className="brand-mark">A</span><span>AI Finance <em>OS</em></span></Link><Link className="text-link" href="/dashboard"><ArrowLeft size={14} /> Retour au dashboard</Link></div><div className="expenses-heading"><div><p className="eyebrow">FINANCE</p><h1>Dépenses</h1><p>Suivez les sorties réellement enregistrées.</p></div><button className="button button-dark" onClick={() => setShowForm((current) => !current)}><Plus size={16} />Ajouter une dépense</button></div>{message && <p className="invoice-message success" role="status">{message}</p>}<div className="expense-total"><small>Total affiché</small><strong>{total.toLocaleString("fr-FR", { style: "currency", currency: "EUR" })}</strong></div>{showForm && <form className="expense-form" onSubmit={create}><h2>Nouvelle dépense</h2><div className="form-grid"><label>Date<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>Catégorie<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label></div><label>Description<input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} required /></label><label>Montant<input type="number" min="0" step="0.01" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} required /></label><button className="button button-dark" disabled={isSaving}>{isSaving ? "Enregistrement..." : "Enregistrer"}</button></form>}<label className="expense-search"><Search size={16} /><input placeholder="Rechercher une dépense" value={search} onChange={(event) => setSearch(event.target.value)} /></label>{isLoading ? <p className="expense-empty">Chargement...</p> : visible.length === 0 ? <p className="expense-empty">Aucune dépense réelle pour le moment.</p> : <div>{visible.map((expense) => <article className="expense-row" key={expense.id}><span><strong>{expense.description}</strong><small>{expense.category}</small></span><span>{expense.expense_date ? new Date(`${expense.expense_date}T00:00:00`).toLocaleDateString("fr-FR") : "Sans date"}</span><strong>{Number(expense.amount).toLocaleString("fr-FR", { style: "currency", currency: expense.currency })}</strong><div className="expense-actions"><button className="icon-button" aria-label={`Supprimer ${expense.description}`} onClick={() => void remove(expense.id)}><Trash2 size={16} /></button></div></article>)}</div>}</div></main>;
}
